version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    environment:
      POSTGRES_DB: greendale-academic
      POSTGRES_USER: greendale
      POSTGRES_PASSWORD: academic
    volumes:
      - dados-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dados-postgres: